# Generated by Django 3.1.7 on 2021-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='default_email',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
