# Generated by Django 3.1.7 on 2021-03-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_patron_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='default_email',
            field=models.EmailField(max_length=254),
        ),
    ]
