# Generated by Django 3.1.7 on 2021-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('artist_id', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sold', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('PA', 'Painting'), ('DR', 'Drawing'), ('CE', 'Ceramics'), ('SC', 'Sculpture'), ('PR', 'Prints'), ('CA', 'Cards'), ('BO', 'Books'), ('MX', 'Mixed')], default='PA', max_length=2)),
                ('created_at', models.DateTimeField()),
                ('image_path', models.URLField(blank=True, max_length=1024)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
