# Generated by Django 3.1.7 on 2021-03-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworks',
            options={'verbose_name_plural': 'Artworks'},
        ),
    ]
