# Generated by Django 3.1.7 on 2021-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210313_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
