# Generated by Django 3.1.7 on 2021-03-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210318_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_number',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='line_number',
        ),
    ]
