# Generated by Django 3.1.7 on 2021-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email_address', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('admin_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
