# Generated by Django 3.1.7 on 2021-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210330_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='year',
            field=models.IntegerField(help_text='2021 onwards'),
        ),
    ]
